apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

#  - name: Loki
#    uid: Loki
#    type: loki
#    access: proxy
#    url: http://loki:3100
#
#  - name: Tempo
#    uid: Tempo
#    type: tempo
#    access: proxy
#    url: http://tempo:3200
#    jsonData:
#      httpMethod: POST
#      useGRPC: false
#      grpc: false
#      tracesToLogs:
#        datasourceUid: Loki
#        spanStartTimeShift: "1h"
#        spanEndTimeShift: "1h"
#        filterByTraceID: true
#        filterBySpanID: false
#      tracesToMetrics:
#        datasourceUid: Prometheus
#      serviceMap:
#        datasourceUid: Prometheus
#      nodeGraph:
#        enabled: true
